### ISSUE TITLE
Integrate Linting into CI Pipeline and pre-commit to Enhance Code Quality Checks

### ISSUE THREAD

**Issue by SverreNystad** [CogitoNTNU/NEATactics#16]
We need to add a linting step to our Continuous Integration (CI) pipeline to ensure that all pushed code adheres to our coding standards and is free of syntax errors and undefined names. This addition will help prevent common coding issues from being merged into the main codebase, enhancing overall code quality and maintainability.

## Proposed Changes

1. **Update CI Workflow:** Integrate flake8 linting into the CI pipeline. This will be set up to fail the pipeline if linting errors are detected, specifically targeting Python syntax errors or undefined names. Here's is a possible update to the GitHub Actions workflow file:
```yml
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install flake8 pytest
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

- name: Lint with flake8
  run: |
    # stop the build if there are Python syntax errors or undefined names
    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```
This configuration ensures that critical linting errors will fail the build, prompting developers to fix issues before merging their changes.

2. **Pre-commit Hook:** Additionally, consider setting up a pre-commit hook to run linting locally before changes are pushed to the repository. This can help catch issues earlier in the development cycle, reducing CI failures due to linting errors.
Here's is a possible solution:
```bash
#!/bin/sh

# Pre-commit hook to run flake8 linting with specific settings

# Stash non-staged changes to include only staged changes in the flake8 check
git stash -q --keep-index

# Strict check: stop the commit if there are Python syntax errors or undefined names
echo "Running strict flake8 checks..."
flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

# Save the return value from the strict check
STRICT_RETVAL=$?

# General linting with settings from the CI pipeline
echo "Running general flake8 linting..."
flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

# Unstash the non-staged changes stashed earlier
git stash pop -q

# Check if strict linting failed
if [ $STRICT_RETVAL -ne 0 ]
then
    echo "Strict flake8 linting failed. Your commit will be aborted."
    echo "Fix the reported issues before committing."
    exit 1
fi

echo "Linting passed."
exit 0
```

**Acceptance Criteria:**
- [ ] Update the CI pipeline to use linting.
- [ ]  Add scripts/pre-commit.sh for local linting.
- [ ]  Document the setup process for using the pre-commit hooks in the developer guide.

**Comment by SverreNystad** [comment]
Rather use .pre-commit-config.yaml like in all the new projects:
```yml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)^(
      docs/site/.*|       # Exclude mkdocs compiled files
      docs/docs/jupyter-notebooks_files/.*|       # Exclude Jupyter Notebooks files
      jupyter-experiments/.*|       # Exclude jupyter-experiments
      \.history/.*|       # Exclude history files
      .*cache.*/.*|       # Exclude cache directories
      .*venv.*/.*|        # Exclude virtual environment directories
  )$
fail_fast: true
default_language_version:
  python: python3.12
default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # Filesystem Checks
      - id: check-executables-have-shebangs
        name: "📁 filesystem/⚙️ exec · Verify shebang presence"
      - id: check-shebang-scripts-are-executable
        name: "📁 filesystem/⚙️ exec · Verify script permissions"
      - id: check-case-conflict
        name: "📁 filesystem/📝 names · Check case sensitivity"
      - id: check-illegal-windows-names
        name: "📁 filesystem/📝 names · Validate Windows filenames"
      - id: check-symlinks
        name: "📁 filesystem/🔗 symlink · Check symlink validity"
      - id: destroyed-symlinks
        name: "📁 filesystem/🔗 symlink · Detect broken symlinks"
      - id: check-yaml
        name: "📁 filesystem/📝 yaml · Validate YAML files"
        types: [yaml]
      - id: check-json
        name: "📁 filesystem/📝 json · Validate JSON files"
      - id: check-ast
        name: "🐍 python/📝 ast · Validate Python syntax"
        description: simply checks whether the files parse as valid python.
      # ------------------------------- 🌳 Git Tools ------------------------------- #
      - id: check-merge-conflict
        name: "🌳 git · Detect conflict markers"
      - id: forbid-new-submodules
        name: "🌳 git · Prevent submodule creation"

  # --------------------------- 🔍 Code Quality Tools -------------------------- #

  ### Python Tools
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.5
    hooks:
      - id: ruff-check
        name: "🐍 python · Check with Ruff"
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        name: "🐍 python · Format with Ruff"
        types_or: [ python, pyi ]
        exclude: |
          (?x)^(
            .*\{\{.*\}\}.*|     # Exclude any files with cookiecutter variable, this is an issue with ruff
          )$
  ### Notebooks ###
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa
        entry: nbqa mdformat
        name: "📓 notebook · Format markdown cells"
        args: ["--nbqa-md"]
        types: [jupyter]
        additional_dependencies:
          - mdformat
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff

  ### Data & Config Validation ###
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.2
    hooks:
      - id: check-github-workflows
        name: "🐙 github-actions · Validate gh workflow files"
        args: ["--verbose"]
      - id: check-taskfile
        name: "✅ taskfile · Validate Task configuration"

  ### Markdown ###
  - repo: https://github.com/hukkin/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        name: "📝 markdown · Format markdown"
        additional_dependencies:
          - mdformat-gfm
          - mdformat-ruff
          - mdformat-frontmatter
          - ruff

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        name: "🐍 python · Validate pyproject.toml"
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  # ----------------------------- ⚡️ uv Build Tools ---------------------------- #
  # This helps ensure cross-compatibility with people who don't wish to use uv
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.27
    hooks:
      # STRICT -- This (kind of) enforces use of uv
      - id: uv-sync
        name: "⚡️ uv · Sync dependencies with uv"
      # Update the uv lockfile
      - id: uv-lock
        name: "⚡️ uv · Update dependency lockfile"
      # Export to txt
      - id: uv-export
        name: "⚡️ uv · Export dependencies to requirements.txt"


  # ---------------------------------------------------------------------------- #
  #                            📝 Commit Message Hooks                           #
  # ---------------------------------------------------------------------------- #
  #
  # --------------------------- ✍️ Git Commit Quality -------------------------- #

  ### Commit Message Standards ###
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.0
    hooks:
      - id: commitizen
        name: "🌳 git · Validate commit message"
        stages: [commit-msg]
        additional_dependencies: [cz-conventional-gitmoji]
```
